### PR TITLE
Add export CreateInventory

### PR DESCRIPTION
**Pull request by KadDarem**
Add an export to create inventory from another script

### CODE REVIEW

**Comment by RexShack** [comment]
use : exports['rsg-inventory']:OpenInventory(src, stashName, data)

**Comment by KadDarem** [comment]
This one is to open the inventory UI. 
My export allow to use AddItem export on an inventory you never used before.

**Comment by RexShack** [comment]
the inventory is built on open

**Comment by KadDarem** [comment]
Yeah. So, how can you add a new item to a new stash without opening it first?

**Comment by RexShack** [comment]
why would you want to add an item to a stash that that has not been opened - trying to understand the use case

**Comment by KadDarem** [comment]
Example with an auto-miner script :
* The player can pay to generate items for every 60 s. 
* For every 60 s, a new item is randomly added to the stash. 

=> If the player didn't open the stash before start the miner = Error
=> If the server restarts and I add a new item = Error

**Comment by RexShack** [comment]
ok that makes more sense now

**Comment by KadDarem** [comment]
Thanks for the merge.

**Pull request merged**
