### PR TITLE
Utilize OX_Lib and Code Cleanup

### PR DESCRIPTION
**Pull request by TehGuardian**

### CODE REVIEW

**Comment by RexShack** [comment]
PlayerData.metadata["inlaststand"] does not exist as this was removed

**Comment by TehGuardian** [comment]
*Removed

**Comment by RexShack** [comment]
you are also using cache.ped - not seen that before is this correct?

**Comment by TehGuardian** [comment]
Yeah theres different values to use. 
https://overextended.dev/ox_lib/Modules/Cache/Client

**Pull request merged**
